# Generated by Django 6.0.1 on 2026-01-17 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_add_performance_indexes"),
        ("invitations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["email", "accepted_at"], name="invitations_email_accepted_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(
                fields=["expires_at", "accepted_at"], name="invitations_expiry_idx"
            ),
        ),
    ]
