# Generated by Django 6.0.1 on 2026-01-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_alter_subject_unique_together_and_more"),
        ("invitations", "0003_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="assigned_subjects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Subjects to assign to teacher upon acceptance",
                related_name="invitations",
                to="academic.subject",
            ),
        ),
    ]
