# Generated by Django 6.0.1 on 2026-01-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='For sorting classes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'db_table': 'classes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_class',
            field=models.ForeignKey(blank=True, help_text='Only applicable for students', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.class'),
        ),
    ]
