# Generated by Django 6.0.1 on 2026-01-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_option", models.CharField(max_length=1)),
                ("is_correct", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Exam Answer",
                "verbose_name_plural": "Exam Answers",
                "db_table": "exam_answers",
            },
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_order", models.JSONField(default=list)),
                ("option_orders", models.JSONField(default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("timed_out", "Timed Out"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveIntegerField(blank=True, null=True)),
                ("total_questions", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Exam Attempt",
                "verbose_name_plural": "Exam Attempts",
                "db_table": "exam_attempts",
            },
        ),
    ]
