# Generated by Django 6.0.1 on 2026-01-15 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attempts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="examanswer",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="attempts.examattempt",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together={("exam", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together={("attempt", "question")},
        ),
    ]
