# Generated by Django 6.0.1 on 2026-01-17 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0004_update_selected_option_to_fk"),
        ("exams", "0003_add_performance_indexes"),
        ("questions", "0006_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="examanswer",
            index=models.Index(
                fields=["attempt", "is_correct"], name="answers_attempt_correct_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(fields=["status"], name="attempts_status_idx"),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["student", "status"], name="attempts_student_status_idx"
            ),
        ),
    ]
