# Generated by Django 6.0.1 on 2026-01-17 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0005_add_performance_indexes"),
        ("exams", "0003_add_performance_indexes"),
        ("questions", "0006_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examanswer",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="examanswer",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="unique_answer_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                fields=("exam", "student"), name="unique_attempt_per_student"
            ),
        ),
    ]
