# Generated by Django 6.0.1 on 2026-01-18 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attempts", "0006_alter_examanswer_unique_together_and_more"),
        ("exams", "0005_add_exam_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examattempt",
            name="unique_attempt_per_student",
        ),
        migrations.AddField(
            model_name="examattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name="examattempt",
            index=models.Index(
                fields=["exam", "student"], name="attempts_exam_student_idx"
            ),
        ),
    ]
