# Generated by Django 6.0.1 on 2026-01-17 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_correct_option_to_old(apps, schema_editor):
    """Copy the old correct_option CharField value to correct_option_old before we change it."""
    Question = apps.get_model("questions", "Question")
    for q in Question.objects.all():
        q.correct_option_old = q.correct_option
        q.save(update_fields=["correct_option_old"])


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First, add the correct_option_old field
        migrations.AddField(
            model_name="question",
            name="correct_option_old",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "Option A"),
                    ("B", "Option B"),
                    ("C", "Option C"),
                    ("D", "Option D"),
                ],
                default="",
                max_length=1,
            ),
        ),
        # Copy existing correct_option to correct_option_old
        migrations.RunPython(copy_correct_option_to_old, migrations.RunPython.noop),
        # Add updated_by field
        migrations.AddField(
            model_name="question",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Make old option fields optional
        migrations.AlterField(
            model_name="question",
            name="option_a",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_b",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_c",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="question",
            name="option_d",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        # Remove the old correct_option field
        migrations.RemoveField(
            model_name="question",
            name="correct_option",
        ),
        # Create QuestionOption model
        migrations.CreateModel(
            name="QuestionOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questions.question",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_options_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Option",
                "verbose_name_plural": "Question Options",
                "db_table": "question_options",
            },
        ),
        # Add the new correct_option FK field
        migrations.AddField(
            model_name="question",
            name="correct_option",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="correct_for_questions",
                to="questions.questionoption",
            ),
        ),
    ]
