# Generated by Django 6.0.1 on 2026-01-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_migrate_options_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_option_old",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_a",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_b",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_c",
        ),
        migrations.RemoveField(
            model_name="question",
            name="option_d",
        ),
    ]
