# Generated by Django 6.0.1 on 2026-01-17 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_add_performance_indexes"),
        ("questions", "0005_remove_old_option_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["is_active"], name="questions_active_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["subject", "is_active"], name="questions_subject_active_idx"
            ),
        ),
    ]
