# Generated by Django 6.0.1 on 2026-01-18 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_teacher_assigned_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_published",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when a new exam is published for your class",
                    ),
                ),
                (
                    "exam_reminder",
                    models.BooleanField(
                        default=True,
                        help_text="Receive reminder email 24 hours before exam starts",
                    ),
                ),
                (
                    "result_available",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email when your exam result is available",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notification_preferences",
            },
        ),
    ]
