# Generated by Django 6.0.1 on 2026-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(fields=["email", "otp"], name="otp_email_otp_idx"),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(fields=["expires_at"], name="otp_expires_idx"),
        ),
    ]
