# Generated by Django 6.0.1 on 2026-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="cached_student_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(fields=["is_active"], name="classes_active_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(fields=["is_active"], name="subjects_active_idx"),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["assigned_class", "is_active"], name="subjects_class_active_idx"
            ),
        ),
    ]
