# Generated by Django 6.0.1 on 2026-01-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("assigned_class", "name"), name="unique_subject_per_class"
            ),
        ),
    ]
