# Generated by Django 6.0.1 on 2026-01-17 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0002_add_performance_indexes"),
        ("exams", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(fields=["is_active"], name="exams_active_idx"),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["subject", "is_active"], name="exams_subject_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["status", "is_active"], name="exams_status_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["start_time", "end_time"], name="exams_time_range_idx"
            ),
        ),
    ]
