# Generated by Django 6.0.1 on 2026-01-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_add_performance_indexes"),
        ("questions", "0006_add_performance_indexes"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="examquestion",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="examquestion",
            constraint=models.UniqueConstraint(
                fields=("exam", "question"), name="unique_question_per_exam"
            ),
        ),
    ]
