# Generated by Django 6.0.1 on 2026-01-18 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0003_alter_subject_unique_together_and_more"),
        ("exams", "0004_alter_examquestion_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.CharField(
                choices=[("official", "Official"), ("practice", "Practice")],
                default="official",
                help_text="Practice exams can be retaken multiple times",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["exam_type", "is_active"], name="exams_type_active_idx"
            ),
        ),
    ]
